-- Radar SUS
-- Estrutura já usada no projeto. Execute apenas se estiver criando o banco do zero.

create table if not exists public.publicacoes (
  id bigint generated by default as identity primary key,
  fonte text not null default 'CONASEMS',
  data date not null,
  orgao text,
  categoria text,
  relevancia text,
  palavras text,
  portaria text,
  cnes text,
  municipio text,
  valores text,
  titulo text not null,
  resumo text,
  link text not null unique,
  coleta_em timestamptz,
  analise text,
  analise_em timestamptz,
  analise_por uuid references auth.users(id),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index if not exists publicacoes_data_idx on public.publicacoes (data desc);
create index if not exists publicacoes_categoria_idx on public.publicacoes (categoria);
create index if not exists publicacoes_relevancia_idx on public.publicacoes (relevancia);

alter table public.publicacoes enable row level security;

drop policy if exists "Publicacoes podem ser lidas publicamente" on public.publicacoes;
create policy "Publicacoes podem ser lidas publicamente"
on public.publicacoes
for select
to anon, authenticated
using (true);
